### ISSUE TITLE
Comentarios QMP2

### ISSUE THREAD

**Issue by ggallici** [FrancoPaesani/QMP#1]
Buenas, antes que nada perdón por la demora. Te voy marcando un par de cositas fuí viendo en tu solución:

- Como ya se habló en clase, tener a `Material` como clase contenedora de la `Trama` no nos aporta nada. Lo mejor sería que fuera un `enum` independiente y referenciado directamente desde `Prenda` 
- Todavía no es necesario modelar el atuendo dado que no tenemos la suficiente información para saber si va a ser o no una abstracción relevante de nuestro dominio.
- `PrendaBuilder` podría tener un mejor nombre, como `Borrador`. Esto nos ayuda a desacoplar al objeto del patrón que implementa y, a su vez, respetar los nombres de las abstracciones de nuestro dominio.
- La `Prenda` no debería recibir al `PrendaBuilder` en el constructor, es un acoplamiento innecesario. Debería recibir directamente sus atributos.
- https://github.com/FrancoPaesani/QMP/blob/2ada4d7de61af3976fb05f863411b0f1ff3738e8/src/main/java/ar/edu/utn/frba/dds/QMP/Prenda.java#L15-L18
Esta validación debería estar en el constructor del builder, para desacoplar a la prenda de toda la lógica creacional.
- https://github.com/FrancoPaesani/QMP/blob/2ada4d7de61af3976fb05f863411b0f1ff3738e8/src/main/java/ar/edu/utn/frba/dds/QMP/PrendaBuilder.java#L35-L38
    Acá te estás perdiendo la informacion de cual dependencia estaba en estado inconsistente. Para atacar esto, lo que podrias hacer es hacer un `Objects.requireNonNull` o un `if + throw` en cada uno de los steps del builder.
- También estás permitiendo que se setee una `Trama` inconsistente con un `builder.setTrama(null)`
- con respecto al **bonus**: 
    - Acá un builder no nos resuelve ninguno de los problemas que tenemos. Lo que sí nos vendría bien es un factory method donde pudiera tener un `crearUniforme` con distintas configuraciones por cada institución.
    - También tené en cuenta que en el uniforme estas guardando una lista de categorías, cuando en realidad un uniforme debería estar formado por 3 y solo 3 prendas.

**Comment by FrancoPaesani** [comment]
Buenas German!
Si, estuve cambiando los errores que marcaste + lo que vimos en clase. Y organizandolo un poco más en paquetes así es más facil para las proximas entregas.

El tema de los uniformes lo había pensado en hacer un factory pero terminé con otro builder (que como decis vos, no me ayudaba en nada el builder en este caso). Y lo había modelado como una lista por si se tenía chomba+buzo+campera. Pero sobrediseñé ahí seguramente, por lo que decía el enunciado.

Gracias, saludos!!
